---
services:
  eth-devnet:
    container_name: eth-devnet
    image: node:lts-alpine
    command: sh -c "npx hardhat node"
    volumes:
      - ./hardhat.config.js:/hardhat/hardhat.config.js
      - ./package.json:/hardhat/package.json
      - ./package-lock.json:/hardhat/package-lock.json
      - "./node_modules:/hardhat/node_modules:ro"
    working_dir: /hardhat
    ports:
      - '8545:8545'
    env_file: .env
    healthcheck:
      test: [ "CMD", "npx", "hardhat", "check" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  ui:
    container_name: ui
    command: sh -c "npm run start:ui"
    image: node:lts-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./.babelrc.js:/ui/.babelrc.js
      - ./dist:/ui/dist
      - "./node_modules:/ui/node_modules:ro"
      - ./package.json:/ui/package.json
      - ./package-lock.json:/ui/package-lock.json
      - ./public:/ui/public
      - ./src:/ui/src
      - ./tsconfig.json:/ui/tsconfig.json
      - ./webpack.config.babel.js:/ui/webpack.config.babel.js
      - ./webpack:/ui/webpack
    working_dir: /ui
    healthcheck:
      test: [ "CMD", "wget", "localhost:3000", "-O", "/dev/null" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s


  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.9.0
    ports:
      - "5008:5001"
      - "8085:8080"
      # - "4001:4001" # ipfs swarm - expose if needed/wanted
    volumes:
      - ./.ipfs:/data/ipfs
    healthcheck:
      test: [ "CMD", "wget", "-S", "-O", "/dev/null",
              "http://localhost:8080/ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
