// Theme color constants
export const THEME_COLOR_PRIMARY_MAIN = '#2286A5'

export const THEME_COLOR_SECONDARY_MAIN = '#61A454'

export const THEME_COLOR_WARNING_MAIN = '#C79C36'

export const THEME_COLOR_SUCCESS_MAIN = '#3C763D'

export const THEME_COLOR_ERROR_MAIN = '#B53939'

export const THEME_BACKGROUND_DEFAULT = '#ffffff'
export const THEME_BACKGROUND_PAPER = '#ffffff'

export const THEME_SHAPE_BORDER_RADIUS = 8
export const THEME_DARK_COLOR_PRIMARY_MAIN = '#ffffff'

export const THEME_DARK_TEXT_PRIMARY = 'rgba(255,255,255,0.8)'
export const THEME_DARK_TEXT_SECONDARY = 'rgba(255,255,255,0.5)'

export const THEME_DARK_ACTION_ACTIVE = '#FFF'
export const THEME_DARK_ACTION_HOVER = 'rgba(255,255,255,0.08)'
export const THEME_DARK_ACTION_HOVER_OPACITY = 0.08
export const THEME_DARK_ACTION_SELECTED = 'rgba(255,255,255,0.16)'
export const THEME_DARK_ACTION_SELECTED_OPACITY = 0.16
export const THEME_DARK_ACTION_DISABLED = 'rgba(255,255,255,0.3)'
export const THEME_DARK_ACTION_DISABLED_BACKGROUND = 'rgba(255,255,255,0.12)'
export const THEME_DARK_ACTION_DISABLED_OPACITY = 0.38
export const THEME_DARK_ACTION_FOCUS = 'rgba(255,255,255,0.12)'
export const THEME_DARK_ACTION_FOCUS_OPACITY = 0.12
export const THEME_DARK_ACTION_ACTIVATED_OPACITY = 0.24

export const THEME_DARK_BACKGROUND_DEFAULT = '#121212'
export const THEME_DARK_BACKGROUND_PAPER = 'rgb(30 30 30)'

export const THEME_DARK_DIVIDER = 'rgba(255,255,255,0.3)'
