// import {Genres, Images} from "@state/movies/types";

import { GenresList } from '@state/movies/types';

export const MOVIE_EXTRA_FIELDS_LIMIT = 5;
export const FAKE_MOVIES = [
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Help',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'El origen de Gru',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/39175/dblmzk8OhtD5xHJy9HD82Vkj5KnKA50SMtJAxApl.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/39175/dblmzk8OhtD5xHJy9HD82Vkj5KnKA50SMtJAxApl.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/39175/dblmzk8OhtD5xHJy9HD82Vkj5KnKA50SMtJAxApl.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Película Elvis',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/38887/nyDVdGNjzYBhThcTeXSIoXjY6cgPGOrTxsF2oWCp.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/38887/nyDVdGNjzYBhThcTeXSIoXjY6cgPGOrTxsF2oWCp.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/38887/nyDVdGNjzYBhThcTeXSIoXjY6cgPGOrTxsF2oWCp.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Doctor Strange',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/24926/sVDzVWEnjWgGlHEUrYxvfu7Vz8WTcTvlNyoiU3QJ.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/24926/sVDzVWEnjWgGlHEUrYxvfu7Vz8WTcTvlNyoiU3QJ.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/24926/sVDzVWEnjWgGlHEUrYxvfu7Vz8WTcTvlNyoiU3QJ.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Jurassic World',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Lightyear',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/36713/tjhuspxvcQr9XpRVXh6sxyHS4qdbZFsh0YUMunb3.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/36713/tjhuspxvcQr9XpRVXh6sxyHS4qdbZFsh0YUMunb3.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/36713/tjhuspxvcQr9XpRVXh6sxyHS4qdbZFsh0YUMunb3.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'El hombre del norte',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Los Tipos Malos',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
    },
  },
];

export const FAKE_MOVIES_2 = [
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'El hombre del norte',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/20528/wpYnoyLsoAkPMaG2YODF47VYCyToYmBI4SnOc6Qx.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Jurassic World',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/33380/92D77KV0QPr10oVaKV3ncZuNCOYYXJYzhALfmIW2.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Los Tipos Malos',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/23844/PRGLhdrn5kAvKL3cn8iEe2mlZJFqIcWkbxmPMftb.jpg',
    },
  },
  {
    creator: '0x0010',
    description: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    path: 'test path',
    title: 'Help',
    date_uploaded_unix: 1234,
    price: 1,
    group_name: 'test group',
    imdb_code: 'code123',
    language: 'en',
    mpa_rating: 'rating123',
    rating: 123,
    runtime: 12344,
    synopsis: 'Tras los sucesos de “Vengadores: Infinity War”, los superhéroes que sobrevivieron a Thanos se reunen para poner en práctica un plan definitivo que podría acabar con el villano definitivamente. No saben si funcionará, pero es su única oportunidad de intentarlo. Cuarta entrega de la saga “Vengadores”',
    trailer_code: 'test',
    year: 2022,
    token: '12344',
    genres: GenresList[1],
    posters: {
      small: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
      medium: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
      large: 'https://ww3.cuevana.pro/resize/200/storage/29919/AkcCfKprN4Sxf4fu7GAZatgmtAaReLSOTwrzduSL.jpg',
    },
  },
];
