export { default as TopHeader } from '@components/TopHeader'
export { default as MainSlider } from '@components/MainSlider'
export { default as RoundButton } from '@components/RoundButton'
export { default as WalletButton } from '@components/WalletButton'
export { default as Logo } from '@components/Logo'
