export const ROOT = '/'
export const EXPLORE = '/explore'
export const FESTIVAL = '/festival'
export const SELL = '/sell'
export const WORK = '/work'
export const MOVIE = '/:id'
export const MOVIE_CREATE = '/create'
