export const ROOT = '/'
export const EXPLORE = '/explore'
export const CREATE = '/create'
export const FESTIVAL = '/festival'
export const SELL = '/sell'
export const WORK = '/work'
export const MOVIE = '/m/:id'
