export * from '@material-ui/icons'
export { IconLogOut } from '@components/Icons/custom/IconLogOut'
export { IconBox } from '@components/Icons/custom/IconBox'
export { IconDiamond } from '@components/Icons/custom/IconDiamond'
export { IconWrapper } from '@components/Icons/custom/IconWrapper'
