---
name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hardhat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make test
        env:
          LOCALHOST_CONTRACT_NFT: ${{ secrets.LOCALHOST_CONTRACT_NFT }}
          LOCALHOST_CONTRACT_FT: ${{ secrets.LOCALHOST_CONTRACT_FT }}
          HARDHAT_AUTOMINE: "true"
      - name: docker-compose logs on failure
        if: ${{ failure() }}
        run: docker-compose logs

  testnet:
    runs-on: ubuntu-latest
    needs: hardhat
    strategy:
      fail-fast: false
      matrix:
        network: [rinkeby]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test:${{ matrix.network }}
        env:
          GOERLI_ALCHEMY_API_KEY: ${{ secrets.GOERLI_ALCHEMY_API_KEY }}
          KOVAN_ALCHEMY_API_KEY: ${{ secrets.KOVAN_ALCHEMY_API_KEY }}
          RINKEBY_ALCHEMY_API_KEY: ${{ secrets.RINKEBY_ALCHEMY_API_KEY }}
          ROPSTEN_ALCHEMY_API_KEY: ${{ secrets.ROPSTEN_ALCHEMY_API_KEY }}
          OWNER_KEY: ${{ secrets.OWNER_KEY }}
          SECONDARY_KEY: ${{ secrets.SECONDARY_KEY }}
