---
name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hardhat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make test

  testnet:
    runs-on: ubuntu-latest
    needs: hardhat
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        network: [ropsten, rinkeby]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test:${{ matrix.network }}
        env:
          RINKEBY_ALCHEMY_API_KEY: ${{ secrets.RINKEBY_ALCHEMY_API_KEY }}
          ROPSTEN_ALCHEMY_API_KEY: ${{ secrets.ROPSTEN_ALCHEMY_API_KEY }}
          OWNER_KEY: ${{ secrets.OWNER_KEY }}
          SECONDARY_KEY: ${{ secrets.SECONDARY_KEY }}
          RINKEBY_CONTRACT_NFT: ${{ secrets.ROPSTEN_CONTRACT_NFT }}
          RINKEBY_CONTRACT_FT: ${{ secrets.RINKEBY_CONTRACT_FT }}
          ROPSTEN_CONTRACT_NFT: ${{ secrets.ROPSTEN_CONTRACT_NFT }}
          ROPSTEN_CONTRACT_FT: ${{ secrets.ROPSTEN_CONTRACT_FT }}
