---
name: Build and Test UI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  buildAndTest:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci

      - name: Check
        run: npm run check:js

      - name: Build
        run: npm run build:ui

      - name: Test
        run: npm run test:ui
